import {describe,it,expect} from 'vitest';
import {commandHeader} from '../src/ui/commandHeader.js';
import {createMission,getPlayerView,PHASES} from '../src/sim/company/engine.js';
import {companyAssault} from '../src/scenarios/companyAssault.js';
const fixture=()=>{const state=createMission(companyAssault,'header');return {state,props:{v:getPlayerView(state),name:id=>id,seed:'header',recovery:{},recoveryPending:false,locked:false,combatBlocked:false,advanceLabel:'Resolve segment',phaseIndex:0,progress:null,feedback:'Ready',feedbackKind:'Status'}};};
describe('Compact command header',()=>{
 it('renders existing file controls in an overlay without changing simulation',()=>{const {state,props}=fixture(),before=structuredClone(state),view=structuredClone(props.v),html=commandHeader(props);for(const id of ['seed','restart','export','resume','restore','save-export','previous-export'])expect(html).toContain(`id="${id}"`);expect(html).toContain('id="panel-file"');expect(html).toContain('Game settings coming later');expect(state).toEqual(before);expect(props.v).toEqual(view);});
 it('preserves progression labels and disables progression for review, recovery and HQ choice',()=>{const {props}=fixture();for(const patch of [{locked:true},{combatBlocked:true},{v:{...props.v,eligible_hqs:['hq1']}}]){const html=commandHeader({...props,...patch,advanceLabel:'Continue to cleanup'});expect(html).toMatch(/id="advance"[^>]*disabled/);expect(html).toContain('Continue to cleanup');}});
 it('shows separate reserves and current expenditure',()=>{const {props}=fixture();props.v.impulse={hq:'co',commands:3,spent:2};props.v.units.find(u=>u.id==='hq1').saved=4;const html=commandHeader(props);expect(html).toContain('4 saved');expect(html).toContain('3 available · 2/6 spent');expect(html).toContain('co · 2/6 spent');});
 it('escapes feedback and distinguishes order from previous-segment results',()=>{const {props}=fixture();expect(commandHeader({...props,feedbackKind:'Last order',feedback:'Move <failed>'})).toContain('Move &lt;failed&gt;');expect(commandHeader({...props,feedbackKind:'Previous segment'})).toContain('<b>Previous segment</b>');});
 it('keeps recovery metadata and mission information inspectable',()=>{const {props}=fixture();props.recovery={raw:'record',bundle:{latest:{turn:2,phase:'COMBAT_EFFECTS',timestamp:'today'},turnStart:{turn:2,phase:'FRIENDLY_EVENT',timestamp:'earlier'}}};const html=commandHeader(props);expect(html).toContain('Latest: turn 2');expect(html).toContain(props.v.briefing);expect(html).toContain(PHASES[0][1]);expect(html).toContain('Progress saves automatically');});
});
