import { describe,it,expect } from 'vitest';
import { companyAssault } from '../src/scenarios/companyAssault.js';
import { createMission,advancePhase,endTurn,submitCommand,selectHQ,getPlayerView,getVisibleEvents,abortMission,exportReplay,replayMission,checkObjective } from '../src/sim/company/engine.js';
import { cards,draw,emit } from '../src/sim/company/core.js';
import { refresh,communication,combatModifier,spot,los,basicValue } from '../src/sim/company/battlefield.js';
import { applyHit,resolveCombat,resolveContacts,prepareCombat,resolvePreparedCombat } from '../src/sim/company/combat.js';
import { rally,grenade } from '../src/sim/company/actions.js';
const fresh=()=>createMission(companyAssault,'company-1');
function commandStart(){let s=fresh();for(let i=0;i<4;i++)s=advancePhase(s).state;return s;}
function enemy(s,id='test_enemy',location='r2c1'){
 const u=structuredClone(s.units.mg1);Object.assign(u,{id,name:'Hidden German MG',location,faction:'enemy',fire:'r1c1',cover:null});s.units[id]=u;return u;
}
function stack(s,ids){s.deck.order=[...ids,...s.deck.order.filter(id=>!ids.includes(id))];}
describe('Company assault acceptance',()=>{
 it('creates the course, eight PCs and six multistep squads',()=>{const s=fresh();expect(Object.keys(s.locations)).toHaveLength(16);expect(Object.keys(s.contacts)).toHaveLength(8);expect(Object.values(s.units).filter(u=>u.kind==='SQUAD')).toHaveLength(6);expect(s.units.s11.steps).toHaveLength(3);});
 it('validates the 50 cards and all random/combat columns',()=>{expect(Object.keys(cards)).toHaveLength(51);for(const c of Object.values(cards).filter(c=>c.id!==51)){expect(c.combat).toHaveLength(11);expect(c.combat.every(r=>['MISS','PIN','HIT'].includes(r))).toBe(true);c.random.forEach((n,i)=>expect(n>=1&&n<=i+2).toBe(true));}expect(cards[35].activated).toBe(3);expect(cards[20].combat[5]).toBe('PIN');expect(cards[14].hit.Line).toBe('LC');});
 it('finishes draw batches past reshuffle and draws through deck exhaustion',()=>{const s=fresh();stack(s,[51,1,2]);expect(draw(s,2,'batch').map(c=>c.id)).toEqual([1,2]);expect(s.deck.order).toHaveLength(51);expect(s.deck.reshuffles).toBe(1);expect(draw(s,120,'exhaustion')).toHaveLength(120);});
 it('lets Company HQ activate both platoons and select their order',()=>{let s=commandStart();s.impulse.commands=6;for(const target_id of ['hq1','hq2']){const r=submitCommand(s,{type:'ACTIVATE',unit_id:'co',issuer_id:'co',target_id});expect(r.accepted).toBe(true);s=r.state;}s=advancePhase(s).state;expect(s.phase).toBe('SUBORDINATE_ACTIVATION');s=selectHQ(s,'hq2').state;expect(s.impulse.hq).toBe('hq2');});
 it('rejects distant squad orders without consuming cards or commands',()=>{const s=commandStart();s.units.s11.location='r3c4';const r=submitCommand(s,{type:'MOVE',unit_id:'s11',issuer_id:'co',target_id:'r3c3'});expect(r.accepted).toBe(false);expect(r.state).toBe(s);});
 it('enforces same-area voice and radio LOS/cover, with a rally exception',()=>{const s=fresh(),a=s.units.hq1,b=s.units.s11;a.location=b.location='r1c1';expect(communication(s,a,b)).toBeTruthy();b.pinned=true;expect(communication(s,a,b)).toBeNull();expect(communication(s,a,b,true)).toBeTruthy();a.location='r2c3';s.units.co.location='r1c3';expect(communication(s,s.units.co,a)).toBeTruthy();a.cover='cover';expect(communication(s,s.units.co,a)).toBeNull();});
 it('bounds expenditure and saves Line commands; general initiative is discarded',()=>{let s=commandStart();s.impulse.commands=20;s=advancePhase(s).state;expect(s.units.co.saved).toBe(6);s=fresh();s.phase='GENERAL_INITIATIVE';s.impulse={id:'x',hq:'general',commands:4,spent:0};s=advancePhase(s).state;expect(s.impulse).toBeNull();expect(s.units.co.saved).toBe(0);});
 it('uses strongest fire plus one crossfire modifier rather than addition',()=>{const s=fresh(),u=s.units.s11;u.location='r1c1';enemy(s);enemy(s,'e2','r2c2');refresh(s);const m=combatModifier(s,u);expect(m.parts.fire).toBe(-1);expect(m.parts.crossfire).toBe(-1);expect(m.ncm).toBe(-2);});
 it('pinning a supporting-fire target reduces danger for the maneuver unit',()=>{const s=fresh(),u=s.units.s11;u.location='r1c1';const e=enemy(s);refresh(s);const before=combatModifier(s,u).ncm;e.pinned=true;refresh(s);expect(combatModifier(s,u).ncm).toBeGreaterThan(before);});
 it('resolves mutual fire from one frozen snapshot and ignores object insertion order',()=>{const s=fresh();s.units.s11.location='r1c1';const e=enemy(s);spot(s,e);refresh(s);const reverse=structuredClone(s);reverse.units=Object.fromEntries(Object.entries(reverse.units).reverse());resolveCombat(s);resolveCombat(reverse);expect(reverse.events).toEqual(s.events);expect(s.events.filter(e=>e.type==='COMBAT_RESOLVED').length).toBeGreaterThanOrEqual(2);});
 it('MISS removes pin, with automatic recovery outside incoming fire',()=>{let s=fresh();s.units.s11.location='r1c1';enemy(s);refresh(s);s.units.s11.pinned=true;prepareCombat(s);const resolution=s.pending_combat.find(r=>r.target_id==='s11');resolution.ncm=6;resolvePreparedCombat(s,resolution.id);expect(resolution.result).toBe('MISS');expect(s.units.s11.pinned).toBe(false);s=fresh();s.phase='PINNED_RECOVERY';s.units.s11.pinned=true;s=advancePhase(s).state;expect(s.units.s11.pinned).toBe(false);});
 it('breaks squads into recoverable teams and preserves named casualty provenance',()=>{const s=fresh();applyHit(s,s.units.s11,'CF');expect(s.units.s11.steps).toHaveLength(0);expect(s.casualties).toHaveLength(1);const teams=Object.values(s.units).filter(u=>u.kind==='LAT');expect(teams).toHaveLength(2);const u=teams[0];u.pinned=false;rally(s,u,u,true);expect(u.cohesion).toBe('A');expect(s.casualties[0].step.personnel).toHaveLength(4);});
 it('weapon and HQ losses change capabilities and radio availability',()=>{const s=fresh();applyHit(s,s.units.at1,'F');expect(basicValue(s.units.at1)).toBe(2);s.units.at1.pinned=false;rally(s,s.units.at1,s.units.at1,true);expect(s.units.at1.cohesion).toBe('GOOD');applyHit(s,s.units.co,'C');expect(s.units.co.radios).toEqual([]);expect(s.assets.length).toBeGreaterThan(0);});
 it('activates pending support, then expires it in the following update',()=>{let s=fresh();s.support.push({id:'m',source:'mtrfo',location:'r2c1',status:'PENDING',value:-3});s.phase='FIRE_MISSIONS';s=advancePhase(s).state;expect(s.support[0].status).toBe('ACTIVE');expect(los(s,'r2c1','r1c1')).toBe(false);s.phase='FIRE_MISSIONS';s=advancePhase(s).state;expect(s.support).toEqual([]);});
 it('grenades place deferred combat effects and permit a response',()=>{const s=fresh();s.units.s11.location='r1c1';const e=enemy(s,'e','r1c1');spot(s,e);const before=e.steps.length;grenade(s,s.units.s11,e);expect(e.steps.length).toBe(before);expect(s.markers.length).toBeGreaterThan(0);expect(s.events.filter(e=>e.type==='GRENADE_ATTEMPT')).toHaveLength(2);});
 it('hides attacker identity and causal references while showing incoming fire',()=>{const s=fresh();s.units.s11.location='r1c1';enemy(s);refresh(s);const hidden=emit(s,'PRIVATE','secret',{},true);emit(s,'PUBLIC','Incoming fire',{caused_by_event_id:hidden.id});const serialized=JSON.stringify({view:getPlayerView(s),events:getVisibleEvents(s)});expect(serialized).not.toContain('test_enemy');expect(serialized).not.toContain('Hidden German MG');expect(serialized).not.toContain('secret');expect(getVisibleEvents(s).at(-1).caused_by_event_id).toBeNull();expect(getPlayerView(s).fire.length).toBeGreaterThan(0);});
 it('updates spotted casualties instead of leaving ghost enemy counters',()=>{const s=fresh(),e=enemy(s);spot(s,e);applyHit(s,e,'CC');refresh(s);expect(getPlayerView(s).enemies.find(v=>v.id===e.id).removed).toBe('BROKEN');});
 it('generates contacts in a position that fires on the triggering card',()=>{for(const seed of ['company-1','company-2','company-3']){const s=createMission(companyAssault,seed);s.units.s11.location='r1c1';resolveContacts(s);expect(s.contacts.pc_r1c1.resolved).toBe(true);expect(s.support.length+s.fire.filter(f=>f.target==='r1c1').length).toBeGreaterThan(0);}});
 it('terminates no-contact success, time-limit defeat, force loss and abort',()=>{let s=fresh();for(const c of Object.values(s.contacts))c.resolved=true;s.turn=10;checkObjective(s);expect(s.status).toBe('SUCCESS');s=fresh();s.turn=10;checkObjective(s);expect(s.status).toBe('DEFEAT');s=fresh();for(const u of Object.values(s.units))if(['SQUAD','LAT','MG','AT'].includes(u.kind))u.steps=[];checkObjective(s);expect(s.status).toBe('DEFEAT');expect(abortMission(fresh()).state.status).toBe('ABORTED');});
 it('replays accepted orders, phases and history exactly',()=>{let s=commandStart();s=submitCommand(s,{type:'ACTIVATE',unit_id:'co',issuer_id:'co',target_id:'hq1'}).state;s=endTurn(s).state;s=abortMission(s).state;expect(replayMission(companyAssault,exportReplay(s))).toEqual(s);});
});
