import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {hill192} from '../src/scenarios/hill192.js';
import {replayMission,exportReplay,createMission,prepareReattempt} from '../src/sim/company/engine.js';
import {hill192DeploymentDefinition} from '../src/sim/company/hill192Setup.js';
import {createCampaignRoster,applyMissionDebrief,saveCampaign,readCampaign} from '../src/sim/company/campaignRoster.js';
import {checkpoint,resumeCheckpoint} from '../src/ui/localRecovery.js';
const candidate={...hill192,readiness:{playable:true}};
const read=seed=>JSON.parse(readFileSync(`output/hill192-playtests-v2-r32/${seed}-hill192.json`,'utf8'));
describe('complete Hill 192 legal-order runs',()=>{
 for(const [seed,attempt] of [['hill-route-1',1],['hill-scouted-2',2],['hill-forward-4',2]])it(`${seed}: success, exact replay, recovery and isolated debrief`,()=>{
  const fixture=read(seed),record=fixture.replay,original=structuredClone(record);
  const state=replayMission(candidate,record);
  expect(state.status).toBe('SUCCESS');expect(state.attempt_number).toBe(attempt);
  expect(state.events.findLast(e=>e.type==='OBJECTIVE_CHECK')).toMatchObject({objectives_held:true,rows_clear:true});
  expect(new Set(state.achievements.map(a=>a.key)).size).toBe(state.achievements.length);
  expect(exportReplay(state)).toEqual(record);expect(record).toEqual(original);
  expect(resumeCheckpoint(candidate,checkpoint(state)).state).toEqual(state);
  const definition=hill192DeploymentDefinition(candidate,record.setup);
  const roster=createCampaignRoster(record.roster_snapshot.company_id,definition);
  const data=new Map(),key=hill192.rules.rosterKey,storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};
  storage.setItem('platoon-normandy-st-georges-standalone','accepted M3');saveCampaign(storage,roster,key);
  const next=applyMissionDebrief(roster,state);saveCampaign(storage,next,key,roster.revision);
  expect(readCampaign(storage,key).record).toEqual(next);
  expect(()=>applyMissionDebrief(readCampaign(storage,key).record,state)).toThrow(/already applied/);
  expect(()=>applyMissionDebrief({...roster,revision:1},state)).toThrow(/revision/);
  const raw=storage.getItem(key);expect(()=>saveCampaign({getItem:storage.getItem,setItem:()=>{throw Error('quota');}},{...next,revision:2},key,1)).toThrow('quota');expect(storage.getItem(key)).toBe(raw);
  expect(storage.getItem('platoon-normandy-st-georges-standalone')).toBe('accepted M3');
  const redeployed=createMission(candidate,seed+'-redeploy',record.setup,{mission_instance_id:state.mission_instance_id+'-redeploy',roster:next});
  expect(redeployed.roster_snapshot.people).toEqual(next.people);expect(state.roster_snapshot).toEqual(record.roster_snapshot);
  expect(()=>prepareReattempt(state,{})).toThrow(/No mission reattempt/);
 },120000);
 it('retains the failed battlefield and immutable first record through local preparation',()=>{
  const record=read('hill-scouted-2').replay,index=record.operations.findIndex(op=>op.op==='reattempt');
  expect(index).toBeGreaterThan(0);
  const before=replayMission(candidate,{...record,operations:record.operations.slice(0,index),attempt_records:record.attempt_records.slice(0,1)});
  expect(before.status).toBe('DEFEAT');expect(resumeCheckpoint(candidate,checkpoint(before)).state).toEqual(before);const immutable=structuredClone(before.attempt_records[0]);
  const after=prepareReattempt(before,record.operations[index].choices).state;
  expect(after.attempt_records[0]).toEqual(immutable);expect(after.attempt_records).toEqual(record.attempt_records);
  for(const [id,location] of Object.entries(before.locations))expect(after.locations[id]).toMatchObject({terrain:location.terrain,covers:location.covers});
  for(const [id,l] of Object.entries(before.locations))expect(after.locations[id].mines).toBe(l.mines);
  expect(after.contacts).toEqual(before.contacts);expect(after.registered_targets).toEqual(before.registered_targets);expect(after.enemy_tactics).toBe(hill192.rules.tactics);
  expect(after.support_inventory).toEqual(Object.fromEntries(Object.entries(hill192.support_agencies).map(([id,a])=>[id,a.inventory])));
  expect(Object.keys(record.operations[index].choices.reconstitute)).not.toHaveLength(0);
  expect(after.attempt_points_spent).toBeGreaterThan(0);
  expect(new Set(after.achievements.map(a=>a.key)).size).toBe(after.achievements.length);
  expect(()=>applyMissionDebrief(createCampaignRoster(record.roster_snapshot.company_id,hill192DeploymentDefinition(candidate,record.setup)),before)).toThrow(/reattempt/);
 },120000);
});
