import {describe,it,expect} from 'vitest';
import {hill192} from '../src/scenarios/hill192.js';
import {cerisy} from '../src/scenarios/cerisy.js';
import {stGeorges} from '../src/scenarios/stGeorges.js';
import {createMission,previewMissionSetup,exportReplay,replayMission} from '../src/sim/company/engine.js';
import {exportScoutedBattlefield,saveBattlefield,BATTLEFIELD_KEY} from '../src/sim/company/battlefieldCarryover.js';
import {battlefieldFileRecord,hill192PositionOptions,hill192SetupData,setupMarkup} from '../src/ui/missionSetup.js';
import {hill192DeploymentDefinition} from '../src/sim/company/hill192Setup.js';
import {createCampaignRoster,startStandaloneRoster} from '../src/sim/company/campaignRoster.js';
import {saveRecovery,SAVE_KEY} from '../src/ui/localRecovery.js';
const candidate={...hill192,readiness:{playable:true}};
const source=()=>{const s=createMission(stGeorges,'ui-scouted');s.status='SUCCESS';s.patrol_history=[1,2,3].map(platoon=>({platoon,outcome:'SUCCESS'}));s.locations.r2c2.mines=true;s.events.push({type:'MINEFIELD_FOUND',location:'r2c2'});return {state:s,record:exportScoutedBattlefield(s)};};
const memory=()=>{const entries=new Map();return {entries,getItem:k=>entries.get(k)??null,setItem:(k,v)=>entries.set(k,v)};};
describe('Hill 192 setup and read-only battlefield sources',()=>{
 it('shows no-staging choices and allows the accepted standalone mission',()=>{const p=previewMissionSetup(hill192,'ui'),html=setupMarkup(p,true);expect(html).toContain('Hill 192 battlefield and deployment');expect(html).toContain('No staging area');expect(html).toContain('Reserve · unavailable this mission');expect(html).toContain('name="start-mission"');expect(hill192PositionOptions(p.locations,'r2c3').map(o=>o[0])).toEqual(['r1c1','r1c2','r1c3','r1c4','r1c5','r2c3','RESERVE']);expect(html).toContain('name="hill-concentration"');});
 it('projects source provenance and eligible engineer without exposing private units',()=>{const {record}=source(),before=structuredClone(record),p=previewMissionSetup(hill192,'import',{battlefield:record}),html=setupMarkup(p);expect(html).toContain('Scouted-terrain test');expect(html).toContain('Combat Engineers available');expect(p.units.find(u=>u.id==='engineers').capabilities.engineer).toBe(true);expect(p.units.every(u=>!u.id.startsWith('enemy_'))).toBe(true);expect(record).toEqual(before);});
 it('retains an immutable source in submitted controls and supports forward engineer attachments',()=>{const {record}=source(),data=new Map([['hill-forward','r2c3'],['hill-concentration','r4c1']]),setup=hill192SetupData(data,{battlefield:record});expect(setup.battlefield).toEqual(record);expect(setup.battlefield).not.toBe(record);const s=createMission(candidate,'forward',{...setup,assignments:{engineers:{platoon:1},staff:{platoon:1}},positions:{engineers:'r2c3'}});expect(s.units.engineers.location).toBe('r2c3');expect(s.units.engineers.platoon).toBe(1);expect(replayMission(candidate,exportReplay(s))).toEqual(s);});
 it('rejects malformed/incompatible file data without changing its source',()=>{const {record}=source(),text=JSON.stringify(record);expect(battlefieldFileRecord(text)).toEqual(record);expect(()=>battlefieldFileRecord('{')).toThrow();const bad=structuredClone(record);bad.source.rules_version=99;expect(()=>battlefieldFileRecord(JSON.stringify(bad))).toThrow('source version');expect(JSON.stringify(record)).toBe(text);});
 it('keeps accepted Cerisy staging setup and patrol controls separate',()=>{const c=setupMarkup(previewMissionSetup(cerisy,'cerisy'));expect(c).toContain('Staging');expect(c).not.toContain('hill-import');const p=setupMarkup(previewMissionSetup(stGeorges,'patrol'));expect(p).toContain('Patrolling platoon');expect(p).not.toContain('hill-forward');});
 it('builds the conditional fresh roster before deployment and preserves source stores/recovery',()=>{const {state,record}=source(),storage=memory();saveBattlefield(storage,record);saveRecovery(storage,state,{}, {replace:true});const old=storage.getItem(SAVE_KEY),battlefields=storage.getItem(BATTLEFIELD_KEY);storage.setItem(stGeorges.rules.rosterKey,'accepted-m3-roster');const setup={battlefield:record},definition=hill192DeploymentDefinition(candidate,setup),roster=createCampaignRoster('fresh-m4',definition),s=createMission(candidate,'isolated',setup,{mission_instance_id:'isolated-m4',roster});startStandaloneRoster(storage,roster,definition.rules.rosterKey);saveRecovery(storage,s,{}, {replace:true});expect(storage.getItem(`${SAVE_KEY}-previous`)).toBe(old);expect(storage.getItem(BATTLEFIELD_KEY)).toBe(battlefields);expect(storage.getItem(stGeorges.rules.rosterKey)).toBe('accepted-m3-roster');expect(s.roster_snapshot.formations.engineers).toBeDefined();expect(storage.getItem(definition.rules.rosterKey)).not.toBeNull();});
});

it('preserves the M4 roster and source recovery if isolated replacement writes fail',()=>{const storage=memory(),roster=createCampaignRoster('m4-test',candidate);storage.setItem(candidate.rules.rosterKey,'previous-m4');storage.setItem(SAVE_KEY,'original-m3-recovery');storage.setItem=(key,value)=>{if(key===candidate.rules.rosterKey||key===SAVE_KEY)throw new Error('quota');storage.entries.set(key,value);};expect(()=>startStandaloneRoster(storage,roster,candidate.rules.rosterKey)).toThrow('quota');expect(storage.getItem(candidate.rules.rosterKey)).toBe('previous-m4');const s=createMission(candidate,'failure');expect(()=>saveRecovery(storage,s,{}, {replace:true})).toThrow('quota');expect(storage.getItem(SAVE_KEY)).toBe('original-m3-recovery');expect(storage.getItem(`${SAVE_KEY}-previous`)).toBe('original-m3-recovery');});

it('retains expanded source cards without expanding objectives, starting contacts or fortifications',()=>{const {record}=source(),extra={...structuredClone(record.locations.find(l=>l.id==='r2c2')),id:'r2c6',col:6,outside_boundary:true,covers:[{id:'retained-outside',type:'Trench',value:2,known:true}],mines:true};record.locations.push(extra,{...extra,id:'r5c2',row:5,col:2,covers:[]});const before=structuredClone(record),s=createMission(candidate,'expanded',{battlefield:record});expect(s.locations.r2c6).toMatchObject(extra);expect(s.contacts.pc_r2c6).toBeUndefined();expect(Object.values(s.contacts)).toHaveLength(20);expect(s.boundaries).toEqual({rows:4,columns:5});expect(hill192PositionOptions(previewMissionSetup(hill192,'expanded',{battlefield:record}).locations,'r2c6').some(([id])=>id==='r2c6')).toBe(false);expect(()=>createMission(candidate,'bad',{battlefield:record,objectives:{primary:'r4c6'}})).toThrow();expect(()=>createMission(candidate,'bad',{battlefield:record,forward_defense:'r2c6'})).toThrow('forward defense');expect(replayMission(candidate,exportReplay(s))).toEqual(s);expect(record).toEqual(before);});
